
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AF', 'Afghanistan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AX', 'Åland Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AL', 'Albania');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('DZ', 'Algeria');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AS', 'American Samoa');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AD', 'Andorra');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AO', 'Angola');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AI', 'Anguilla');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AQ', 'Antarctica');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AG', 'Antigua and Barbuda');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AR', 'Argentina');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AM', 'Armenia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AW', 'Aruba');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AC', 'Ascension Island');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AU', 'Australia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AT', 'Austria');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AZ', 'Azerbaijan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BS', 'Bahamas');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BH', 'Bahrain');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BD', 'Bangladesh');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BB', 'Barbados');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BY', 'Belarus');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BE', 'Belgium');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BZ', 'Belize');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BJ', 'Benin');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BM', 'Bermuda');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BT', 'Bhutan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BO', 'Bolivia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BW', 'Botswana');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BR', 'Brazil');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('IO', 'British Indian Ocean Territory');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('VG', 'British Virgin Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BN', 'Brunei');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BG', 'Bulgaria');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BF', 'Burkina Faso');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BI', 'Burundi');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('KH', 'Cambodia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CM', 'Cameroon');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CA', 'Canada');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('IC', 'Canary Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CV', 'Cape Verde');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BQ', 'Caribbean Netherlands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('KY', 'Cayman Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CF', 'Central African Republic');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('EA', 'Ceuta and Melilla');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TD', 'Chad');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CL', 'Chile');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CN', 'China');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CX', 'Christmas Island');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CO', 'Colombia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('KM', 'Comoros');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CG', 'Congo - Brazzaville');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CD', 'Congo - Kinshasa');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CK', 'Cook Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CR', 'Costa Rica');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CI', 'Côte d’Ivoire');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('HR', 'Croatia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CU', 'Cuba');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CW', 'Curaçao');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CY', 'Cyprus');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CZ', 'Czechia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('DK', 'Denmark');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('DG', 'Diego Garcia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('DJ', 'Djibouti');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('DM', 'Dominica');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('DO', 'Dominican Republic');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('EC', 'Ecuador');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('EG', 'Egypt');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SV', 'El Salvador');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GQ', 'Equatorial Guinea');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('ER', 'Eritrea');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('EE', 'Estonia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('ET', 'Ethiopia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('EZ', 'Eurozone');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('FK', 'Falkland Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('FO', 'Faroe Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('FJ', 'Fiji');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('FI', 'Finland');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('FR', 'France');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GF', 'French Guiana');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PF', 'French Polynesia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TF', 'French Southern Territories');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GA', 'Gabon');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GM', 'Gambia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GE', 'Georgia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('DE', 'Germany');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GH', 'Ghana');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GI', 'Gibraltar');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GR', 'Greece');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GL', 'Greenland');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GD', 'Grenada');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GP', 'Guadeloupe');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GU', 'Guam');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GT', 'Guatemala');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GG', 'Guernsey');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GN', 'Guinea');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GW', 'Guinea-Bissau');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GY', 'Guyana');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('HT', 'Haiti');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('HN', 'Honduras');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('HK', 'Hong Kong SAR China');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('HU', 'Hungary');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('IS', 'Iceland');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('IN', 'India');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('ID', 'Indonesia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('IR', 'Iran');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('IQ', 'Iraq');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('IE', 'Ireland');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('IM', 'Isle of Man');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('IL', 'Israel');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('IT', 'Italy');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('JM', 'Jamaica');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('JP', 'Japan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('JE', 'Jersey');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('JO', 'Jordan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('KZ', 'Kazakhstan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('KE', 'Kenya');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('KI', 'Kiribati');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('XK', 'Kosovo');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('KW', 'Kuwait');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('KG', 'Kyrgyzstan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('LA', 'Laos');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('LV', 'Latvia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('LB', 'Lebanon');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('LS', 'Lesotho');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('LR', 'Liberia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('LY', 'Libya');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('LI', 'Liechtenstein');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('LT', 'Lithuania');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('LU', 'Luxembourg');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MO', 'Macau SAR China');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MK', 'Macedonia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MG', 'Madagascar');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MW', 'Malawi');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MY', 'Malaysia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MV', 'Maldives');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('ML', 'Mali');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MT', 'Malta');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MH', 'Marshall Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MQ', 'Martinique');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MR', 'Mauritania');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MU', 'Mauritius');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('YT', 'Mayotte');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MX', 'Mexico');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('FM', 'Micronesia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MD', 'Moldova');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MC', 'Monaco');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MN', 'Mongolia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('ME', 'Montenegro');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MS', 'Montserrat');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MA', 'Morocco');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MZ', 'Mozambique');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MM', 'Myanmar (Burma)');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NA', 'Namibia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NR', 'Nauru');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NP', 'Nepal');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NL', 'Netherlands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NC', 'New Caledonia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NZ', 'New Zealand');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NI', 'Nicaragua');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NE', 'Niger');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NG', 'Nigeria');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NU', 'Niue');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NF', 'Norfolk Island');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('KP', 'North Korea');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MP', 'Northern Mariana Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('NO', 'Norway');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('OM', 'Oman');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PK', 'Pakistan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PW', 'Palau');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PS', 'Palestinian Territories');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PA', 'Panama');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PG', 'Papua New Guinea');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PY', 'Paraguay');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PE', 'Peru');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PH', 'Philippines');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PN', 'Pitcairn Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PL', 'Poland');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PT', 'Portugal');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PR', 'Puerto Rico');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('QA', 'Qatar');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('RE', 'Réunion');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('RO', 'Romania');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('RU', 'Russia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('RW', 'Rwanda');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('WS', 'Samoa');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SM', 'San Marino');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('ST', 'São Tomé and Príncipe');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SA', 'Saudi Arabia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SN', 'Senegal');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('RS', 'Serbia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SC', 'Seychelles');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SL', 'Sierra Leone');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SG', 'Singapore');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SX', 'Sint Maarten');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SK', 'Slovakia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SI', 'Slovenia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SB', 'Solomon Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SO', 'Somalia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('ZA', 'South Africa');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GS', 'South Georgia and South Sandwich Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('KR', 'South Korea');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SS', 'South Sudan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('ES', 'Spain');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('LK', 'Sri Lanka');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('BL', 'St. Barthélemy');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SH', 'St. Helena');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('KN', 'St. Kitts and Nevis');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('LC', 'St. Lucia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('MF', 'St. Martin');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('PM', 'St. Pierre and Miquelon');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('VC', 'St. Vincent and Grenadines');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SD', 'Sudan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SR', 'Suriname');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SZ', 'Swaziland');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SE', 'Sweden');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('CH', 'Switzerland');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('SY', 'Syria');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TW', 'Taiwan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TJ', 'Tajikistan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TZ', 'Tanzania');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TH', 'Thailand');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TL', 'Timor-Leste');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TG', 'Togo');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TK', 'Tokelau');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TO', 'Tonga');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TT', 'Trinidad and Tobago');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TA', 'Tristan da Cunha');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TN', 'Tunisia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TR', 'Turkey');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TM', 'Turkmenistan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TC', 'Turks and Caicos Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('TV', 'Tuvalu');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('UM', 'U.S. Outlying Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('VI', 'U.S. Virgin Islands');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('UG', 'Uganda');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('UA', 'Ukraine');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('AE', 'United Arab Emirates');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('GB', 'United Kingdom');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('UN', 'United Nations');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('US', 'United States');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('UY', 'Uruguay');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('UZ', 'Uzbekistan');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('VU', 'Vanuatu');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('VA', 'Vatican City');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('VE', 'Venezuela');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('VN', 'Vietnam');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('WF', 'Wallis and Futuna');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('EH', 'Western Sahara');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('YE', 'Yemen');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('ZM', 'Zambia');
INSERT IGNORE INTO `countries` (`c_iso`, `c_name`) VALUES ('ZW', 'Zimbabwe');